name: Self Hosted Runner Test

on:
  workflow_dispatch:

jobs:

  test-runner:

    runs-on: [self-hosted, windows, x64]

    steps:

      - name: Show Runner Information
        run: |
          hostname
          whoami
          $PSVersionTable
