name: Self Hosted Runner Test

on:
  workflow_dispatch:

  push:
    branches:
      - Gitrepository0-patch-1

jobs:
  test-runner:
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Show Runner Information
        run: |
          hostname
          whoami
          $PSVersionTable
